language: ruby
cache: bundler
rvm:
- 2.2.2
branches:
  only:
  - master # branch to build
env:
  global:
  - GH_COMMIT_AUTHOR="Travis CI"
  - GH_COMMIT_EMAIL=mik.corcuera@gmail.com
script:
- bundle exec rake travis:script
after_success:
- bundle exec rake travis:after_success